[theme]
primaryColor = "#2E74B5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F8FD"
textColor = "#1F3864"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
