"""
Automated PDF report generation for monthly plant performance.
"""
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)
from datetime import datetime


def generate_monthly_report(
    plant_name,
    plant_location,
    month,
    kpis,
    weather_data=None,
    air_quality=None,
    ai_insights=None,
    output_path='report.pdf'
):
    """Generate a professional monthly report PDF."""

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=2*cm, leftMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm
    )

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name='CustomTitle',
        parent=styles['Title'],
        textColor=colors.HexColor('#1F3864'),
        fontSize=22,
        spaceAfter=20
    ))
    styles.add(ParagraphStyle(
        name='SectionHeader',
        parent=styles['Heading1'],
        textColor=colors.HexColor('#2E74B5'),
        fontSize=14,
        spaceBefore=15,
        spaceAfter=10
    ))

    story = []

    # Title
    story.append(Paragraph("DanCarbon Tech", styles['CustomTitle']))
    story.append(Paragraph(
        f"Monthly Performance Report<br/>{plant_name} — {month}",
        styles['Heading2']
    ))
    story.append(Spacer(1, 0.5*cm))

    # Executive summary
    story.append(Paragraph("1. Executive Summary", styles['SectionHeader']))

    summary_data = [
        ['Metric', 'Value'],
        ['CO₂ separated', f"{kpis.get('co2_separated_t', 0):.1f} tonnes"],
        ['CH₄ recovered', f"{kpis.get('ch4_recovered_t', 0):.1f} tonnes"],
        ['Energy saved', f"{kpis.get('energy_saved_mwh', 0):.1f} MWh"],
        ['CO₂ equivalent avoided', f"{kpis.get('co2_avoided_t', 0):.1f} tonnes"],
        ['Plant uptime', f"{kpis.get('uptime_pct', 0):.1f}%"],
    ]
    t = Table(summary_data, colWidths=[7*cm, 7*cm])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F3864')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1),
         [colors.white, colors.HexColor('#DEEAF6')]),
    ]))
    story.append(t)

    # Environmental data
    if weather_data:
        story.append(Paragraph("2. Environmental Conditions", styles['SectionHeader']))
        env_data = [
            ['Parameter', 'Value'],
            ['Ambient temperature', f"{weather_data.get('temperature', 'N/A')} °C"],
            ['Humidity', f"{weather_data.get('humidity', 'N/A')} %"],
            ['Atmospheric pressure', f"{weather_data.get('pressure', 'N/A')} hPa"],
        ]
        if air_quality:
            env_data.extend([
                ['PM2.5', f"{air_quality.get('PM25', 'N/A')} µg/m³"],
                ['NO₂', f"{air_quality.get('NO2', 'N/A')} µg/m³"],
            ])
        t = Table(env_data, colWidths=[7*cm, 7*cm])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2E74B5')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ]))
        story.append(t)

    # AI insights
    if ai_insights:
        story.append(Paragraph("3. AI Optimisation Insights", styles['SectionHeader']))
        for insight in ai_insights:
            story.append(Paragraph(f"• {insight}", styles['BodyText']))

    # Footer
    story.append(Spacer(1, 1*cm))
    story.append(Paragraph(
        f"Generated by DanCarbon Tech Platform on "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M')}",
        styles['Italic']
    ))

    doc.build(story)
    return output_path
